### ISSUE TITLE
Error installing

### ISSUE THREAD

**Issue by matheusmarnt** [stechstudio/laravel-tiptap#1]
Hi, when trying to install the package in my Laravel project, I got this return: "Could not find a matching version of package stechstudio/laravel-tiptap. Please check the package's spelling, its version restriction and whether the package is available in a stability
  which corresponds to its minimum stability (dev)." How should I proceed?

**Comment by jszobody** [comment]
Hey there. This is a brand new package we're still working on, we haven't created a first public release yet. Sorry about that! We hope to have a stable version out within the next month or two.
